#!/bin/bash

docker run --rm -v $(pwd)/docs/jupiter/datastream/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/html.tmpl:/tmp/html.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/html.tmpl,index.html --proto_path=/protos/ jupiter/datastream/v1/market.proto jupiter/datastream/v1/future_data.proto jupiter/datastream/v1/stock_data.proto jupiter/datastream/v1/index_data.proto jupiter/datastream/v1/transaction.proto jupiter/datastream/v1/order.proto jupiter/datastream/v1/order_queue.proto
docker run --rm -v $(pwd)/docs/jupiter/datastream/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/asciidoc.tmpl:/tmp/asciidoc.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/asciidoc.tmpl,index.adoc --proto_path=/protos/ jupiter/datastream/v1/market.proto jupiter/datastream/v1/future_data.proto jupiter/datastream/v1/stock_data.proto jupiter/datastream/v1/index_data.proto jupiter/datastream/v1/transaction.proto jupiter/datastream/v1/order.proto jupiter/datastream/v1/order_queue.proto
docker run --rm -v $(pwd)/docs/jupiter/datastream/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=markdown,README.md --proto_path=/protos/ jupiter/datastream/v1/market.proto jupiter/datastream/v1/future_data.proto jupiter/datastream/v1/stock_data.proto jupiter/datastream/v1/index_data.proto jupiter/datastream/v1/transaction.proto jupiter/datastream/v1/order.proto jupiter/datastream/v1/order_queue.proto
docker run --rm -v $(pwd)/docs/jupiter/datastream/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=json,doc.json --proto_path=/protos/ jupiter/datastream/v1/market.proto jupiter/datastream/v1/future_data.proto jupiter/datastream/v1/stock_data.proto jupiter/datastream/v1/index_data.proto jupiter/datastream/v1/transaction.proto jupiter/datastream/v1/order.proto jupiter/datastream/v1/order_queue.proto

docker run --rm -v $(pwd)/docs/jupiter/strategy/common/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/html.tmpl:/tmp/html.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/html.tmpl,index.html --proto_path=/protos/ jupiter/strategy/common/v1/factor.proto
docker run --rm -v $(pwd)/docs/jupiter/strategy/common/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/asciidoc.tmpl:/tmp/asciidoc.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/asciidoc.tmpl,index.adoc --proto_path=/protos/ jupiter/strategy/common/v1/factor.proto
docker run --rm -v $(pwd)/docs/jupiter/strategy/common/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=markdown,README.md --proto_path=/protos/ jupiter/strategy/common/v1/factor.proto
docker run --rm -v $(pwd)/docs/jupiter/strategy/common/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=json,doc.json --proto_path=/protos/ jupiter/strategy/common/v1/factor.proto

docker run --rm -v $(pwd)/docs/jupiter/trader/ctp/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/html.tmpl:/tmp/html.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/html.tmpl,index.html --proto_path=/protos/ jupiter/trader/ctp/v1/direction.proto jupiter/trader/ctp/v1/offset_flag.proto jupiter/trader/ctp/v1/hedge_flag.proto jupiter/trader/ctp/v1/instrument.proto jupiter/trader/ctp/v1/investor_position.proto jupiter/trader/ctp/v1/trading_account.proto jupiter/trader/ctp/v1/order.proto jupiter/trader/ctp/v1/order_action.proto jupiter/trader/ctp/v1/trade.proto jupiter/trader/ctp/v1/error.proto
docker run --rm -v $(pwd)/docs/jupiter/trader/ctp/v1:/out -v $(pwd)/jupiter:/protos/jupiter -v $(pwd)/.protoc/template/asciidoc.tmpl:/tmp/asciidoc.tmpl pseudomuto/protoc-gen-doc --doc_opt=/tmp/asciidoc.tmpl,index.adoc --proto_path=/protos/ jupiter/trader/ctp/v1/direction.proto jupiter/trader/ctp/v1/offset_flag.proto jupiter/trader/ctp/v1/hedge_flag.proto jupiter/trader/ctp/v1/instrument.proto jupiter/trader/ctp/v1/investor_position.proto jupiter/trader/ctp/v1/trading_account.proto jupiter/trader/ctp/v1/order.proto jupiter/trader/ctp/v1/order_action.proto jupiter/trader/ctp/v1/trade.proto jupiter/trader/ctp/v1/error.proto
docker run --rm -v $(pwd)/docs/jupiter/trader/ctp/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=markdown,README.md --proto_path=/protos/ jupiter/trader/ctp/v1/direction.proto jupiter/trader/ctp/v1/offset_flag.proto jupiter/trader/ctp/v1/hedge_flag.proto jupiter/trader/ctp/v1/instrument.proto jupiter/trader/ctp/v1/investor_position.proto jupiter/trader/ctp/v1/trading_account.proto jupiter/trader/ctp/v1/order.proto jupiter/trader/ctp/v1/order_action.proto jupiter/trader/ctp/v1/trade.proto jupiter/trader/ctp/v1/error.proto
docker run --rm -v $(pwd)/docs/jupiter/trader/ctp/v1:/out -v $(pwd)/jupiter:/protos/jupiter pseudomuto/protoc-gen-doc --doc_opt=json,doc.json --proto_path=/protos/ jupiter/trader/ctp/v1/direction.proto jupiter/trader/ctp/v1/offset_flag.proto jupiter/trader/ctp/v1/hedge_flag.proto jupiter/trader/ctp/v1/instrument.proto jupiter/trader/ctp/v1/investor_position.proto jupiter/trader/ctp/v1/trading_account.proto jupiter/trader/ctp/v1/order.proto jupiter/trader/ctp/v1/order_action.proto jupiter/trader/ctp/v1/trade.proto jupiter/trader/ctp/v1/error.proto
